chat/urls.py
from django.urls import path
from chat.views import *
from . import views

app_name = 'chat'

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('chat_room/', ChatRoom.as_view(), name="chat_room"),
    path('login/', Login.as_view(), name='login'),
    path("search/", SearchUser.as_view(), name="search_user"),
    path("addfriend/<str:username>", addFriend, name="addfriend"),  
    path("chat/<str:username>", get_message, name="get_message"),
    path('api/messages', UpdateMessage.as_view()),
    path('api/messages/<int:sender>/<int:receiver>', UpdateMessage.as_view()),
]

chat_app/chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name = "index"),
    path("login/", views.login, name = "login"),
    path("signup", views.signup, name = "signup"),
]

chat_app/chat_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("chat.urls"))
]

intern/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from myapp.models import CustomUser


class Friends(models.Model):

    class Meta:
        verbose_name = '友達リスト'
        verbose_name_plural = '友達リスト'

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name = "user_friends")
    friend = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="友達", related_name = "friend_friends")

    def __str__(self):
        return f"{self.friend}"
    
class Messages(models.Model):
    
    description = models.TextField()
    sender_name = models.ForeignKey(CustomUser, verbose_name="送信者", on_delete=models.CASCADE, related_name='sender')
    receiver_name = models.ForeignKey(CustomUser, verbose_name="受信者", on_delete=models.CASCADE, related_name='receiver')
    time = models.TimeField(auto_now_add=True)
    seen = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"To: {self.receiver_name} From: {self.sender_name}"
    
    class Meta:
        ordering = ('timestamp',)
        verbose_name = 'メッセージリスト'
        verbose_name_plural = 'メッセージリスト'

chat/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from myapp.models import CustomUser
from django.views import View
from chat.models import Messages
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.http.response import JsonResponse
from rest_framework.parsers import JSONParser
from chat.serializers import MessageSerializer
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from allauth.account.forms import LoginForm


class UpdateMessage(View):
    
    def post(self, request, *args, **kwargs):
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        
        return JsonResponse(serializer.errors, status=400)
    
    def get(self, request, *args, **kwargs):
        sender = self.kwargs.get('sender')
        receiver =  self.kwargs.get('receiver')
        messages = Messages.objects.filter(sender_name=sender, receiver_name=receiver, seen=False)
        for message in messages:
            message.seen = True
            message.save()
        serializer = MessageSerializer(instance=messages, many=True)
        return JsonResponse(serializer.data, safe=False)


class Home(TemplateView):
    #Home画面を表示するビュー
    template_name = 'myapp/home.html'

class ChatRoom(TemplateView):
    #Home画面を表示するビュー
    template_name = 'chat/chat_box.html'

def getFriendsList(username):
    """
    指定したユーザの友達リストを取得
    :param: ユーザ名
    :return: ユーザ名の友達リスト
    """
    try:
        user = CustomUser.objects.get(username=username)
        friends = list(user.user_friends.all())
        return friends
    except:
        return []
    
class SearchUser(View):
    
    def get(self, request, *args, **kwargs):
        
        if 'search' in self.request.GET:
            query = request.GET.get("search")
            users = list(CustomUser.objects.all())
            user_list = []
            for user in users:
                #検索文字列を含むユーザ情報を取得(自分は除外)
                if query in user.username and user.username != request.user.username:
                    user_list.append(user)
        else:
            user_list = list(CustomUser.objects.all())  #全ユーザ一覧を取得
            for user in user_list:
                if user.username == request.user.username:
                    user_list.remove(user)  #自分のユーザだけ除外
                    break

        friends = getFriendsList(request.user.username)  #自分のフレンド一覧を取得
        return render(request, "chat/search.html", {'friends': user_list, 'friend': friends})
    
# def login_view(request):
#     if request.method == 'POST':
#         # Get all users except the current user
#         user_list = list(CustomUser.objects.exclude(username=request.user.username))
        
#         return render(request, 'chat/search.html', {'friends': user_list})

class Login(TemplateView):
    template_name = 'chat/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = LoginForm()  # フォームインスタンスをコンテキストに追加
        return context

def addFriend(request, username):
    """
    引数で受け取ったユーザ名(username)を Friendsテーブルに友達として登録する。
    """
    login_user = request.user.username
    friend = CustomUser.objects.get(username=username)
    current_user = CustomUser.objects.get(username=login_user)
    friend_lists = current_user.user_friends.all()
    #既に友達登録済みの場合flag=1にセット
    flag = 0
    for friend_list in friend_lists:
        if friend_list.friend.pk == friend.pk:
            flag = 1
            break
    #フレンド未登録の場合
    if flag == 0:
        #お互いにフレンド登録を行う。
        current_user.user_friends.create(friend=friend)  #ログオンユーザ視点でフレンドを登録
        friend.user_friends.create(friend=current_user)   #フレンド視点でログオンユーザをフレンドに登録
    return redirect("chat:search_user")

def get_message(request, username):  
    friend = CustomUser.objects.get(username=username)
    current_user = CustomUser.objects.get(username=request.user.username)
    messages = Messages.objects.filter(sender_name=current_user.id, receiver_name=friend.id) | \
            Messages.objects.filter(sender_name=friend.id, receiver_name=current_user.id)
    friends = getFriendsList(request.user.username)
    
    return render(request, "chat/messages.html",
                    {'messages': messages,
                    'friends': friends,
                    'current_user': current_user, 'friend': friend})

chat_app/chat/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    return render(request, "chat/index.html")

def login(request):
    return render(request, "chat/login.html")

def signup(request):
    return render(request, "chat/signup.html")

chat/templates/chat/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <!-- This file has been downloaded from Bootsnipp.com. Enjoy! -->
    <title>Django Chat</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/chat_room.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  </head>
<body>
<html>
<head>
</head>
<body>
<div class="container">
{% block title%}{% endblock %}
<div class="messaging">
      
        {% block contents%}{% endblock %}
      
      
    </body>
    </html>
<script type="text/javascript"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script type="text/javascript">
  function getCookie(name) {
     var cookieValue = null;
     if (document.cookie && document.cookie !== '') {
         var cookies = document.cookie.split(';');
         for (var i = 0; i < cookies.length; i++) {
             var cookie = jQuery.trim(cookies[i]);
             // Does this cookie string begin with the name we want?
             if (cookie.substring(0, name.length + 1) === (name + '=')) {
                 cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                 break;
             }
         }
     }
     return cookieValue;
 }

 var csrftoken = getCookie('csrftoken');

 function csrfSafeMethod(method) {
     // these HTTP methods do not require CSRF protection
     return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
 }

 $.ajaxSetup({
     beforeSend: function (xhr, settings) {
         if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
             xhr.setRequestHeader("X-CSRFToken", csrftoken);
         }
     }
 });   
</script>
</body>
</html>

chat/templates/chat/chat_box.html
{% extends './base.html' %}
{% load static %}
{% block title %}
<h3 class=" text-center">友達</h3>
{% endblock %}

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

chat/templates/chat/login.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>ログイン</h1>
        <form method="post" action="{% url 'account_login' %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}">
            {% endif %}

            <button type="submit">ログイン</button>
            </form>
    </div>
</body>
</html>

chat/templates/chat/messages.html
{% extends './base.html' %}
{% load static %}
{% block title %}
<h3 class=" text-center">トーク画面</h3>
{% endblock %}
{% block contents %}
<div class="mesgs" style=" width: 40%; position: absolute; left: 50%; transform: translateX(-50%); border: 1px solid black;">
    <div class="msg_history" id="board">
        {% for message in messages %}
        {% if friend == message.sender_name %}
        <div class="incoming_msg">
            <div class="incoming_msg_img"> <img src="{{ friend.thumbnail.url }}" alt="sunil"> </div>
            <div class="received_msg">
                <div class="received_withd_msg">
                    <p style="font-size: 1vw;">{{message.description}}</p>
                    <span class="time_date" style="font-size: 0.8vw;">{{message.time}}</span>
                </div>
            </div>
        </div>
        {% else %}
        <div class="outgoing_msg">
            <div class="sent_msg">
                <p style="font-size: 1vw;">{{message.description}}</p>
                <span class="time_date" style="font-size: 0.8vw;">{{message.time}}</span>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="type_msg">
        <form method="post" class="form-group" id="chat-box">
            {% csrf_token %}
            <div class="input_msg_write">
                <input type="text" class="write_msg" placeholder="メッセージを送信..." name="message" id="msg_field">
                <button type="submit" name="send" class="msg_send_btn"><i class="fa fa-paper-plane-o"
                        aria-hidden="true"></i></button>
            </div>
        </form>
    </div>
</div>

<script>
    //メッセージの送信者（会話相手）と受信者（自分自身）を取得しておく
    sender_id = "{{ friend.id }}";
    receiver_id = "{{ current_user.id }}";
    //画面上に追加するメッセージの定義
    const text_box = '<div class="outgoing_msg">' +
        '<div class="sent_msg">' +
        '<p>{description}</p>' +
        '<span class="time_date">{time}</span>' +
        '</div>' +
        '</div>'

    let messageBody = document.querySelector('.msg_history');
    messageBody.scrollTop = messageBody.scrollHeight - messageBody.clientHeight;
    function scrolltoend() {
        $('#board').stop().animate({
            scrollTop: $('#board')[0].scrollHeight
        }, 800);
    }
    //送信ボタンクリック時の処理を定義
    $(function () {
        $('#chat-box').on('submit', function (event) {
            event.preventDefault();  //ページノリロードを防止
            let message = $('#msg_field');
            //sendメソッドを実行
            send('{{ current_user.id }}', '{{ friend.id }}', message.val());
            message.val(''); //メッセージ入力欄をリセット
        })
    })
    function send(sender, receiver, message){
        //メッセージ送信
        $.post('/api/messages', '{"sender_name": "' + sender + '", "receiver_name": "' +
                receiver + '","description": "' + message + '" }', function (data) {
            let field = text_box.replace('{description}', message);
            let today = new Date();
            let time = today.getHours() + ":" + today.getMinutes();
            field = field.replace('{time}', time);
            $('#board').append(field);

            scrolltoend();
        })
    }
    $(function () {
        setInterval(receive, 1000, '{{friend.thumbnail.url}}')
    })

    const text = '<div class="incoming_ms">' +
        '<div class="incoming_msg_img"> <img src="{thumbnail}" alt="sunil"> </div>' +
        '<div class="received_msg">' +
        '<div class="received_withd_msg">' +
        '<p>{description}</p>' +
        '<span class="time_date">{time}</span>' +
        '</div>' +
        '</div>' +
        '</div>'
        
    function receive(thumbnail){
        $.get('/api/messages/' + sender_id + '/' + receiver_id, function(data){
            if(data.length !== 0){
                for(var i = 0; i < data.length; i++){
                    var field = text.replace('{description}', data[i].description);
                    var time = data[i].time.slice(0, 5)
                    field = field.replace('{time}', time);
                    field = field.replace('{thumbnail}', thumbnail);
                    $('#board').append(field);
                    scrolltoend();
                }
            }
        })
    }
</script>
{% endblock %}

chat/templates/chat/room.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

chat/templates/chat/search.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .chat_list {
            display: flex;
            flex-direction: row;
        }

        .chat_people {
            display: flex;
            align-items: center;
            border: 1px solid black;
            width: 20%;
            margin: 3px;
        }
    </style>
</head>
<body>
    <form method="get">
        {% csrf_token %}
        <div class="input-group mb-3">
            <input type="text" class="form-control-sm" placeholder="ユーザ名で検索" name="search"
                saria-describedby="basic-addon2">
            <button type="submit" class="btn btn-success ml-2">検索</button>
        </div>
    </form>
    {% for friend in friends %}
            <a href="{% url 'chat:get_message' friend.username %}">
        
                <div class="chat_list">
                    <div class="chat_people">
                        <div class="chat_img"> <img src="{{ friend.thumbnail.url }}" alt="sunil" style="width: 30px; height: auto;">
                        </div>
                        <div class="chat_ib">
                            <h5 style="margin-left: 10px;">{{friend.username}}</h5>
                        </div>
                    </div>
                </div>
            </a>
    {% endfor %}
</body>
</html>